blog/urls.py
from django.conf.urls import url
from . import views as core_view
app_name = 'blog'

urlpatterns = [
   url(r'^$', core_view.post_list,  name="blog_list_view"),
   url(r'post/(?P<slug>[-\w]+)/', core_view.post_detail, name="blog_detail"),
   url(r'(?P<slug>[-\w]+)/like/', core_view.PostLikeToggle.as_view(), name="like-toggle"),
   url(r'new-post/', core_view.post_new, name="new_post"),
   url(r'edit/(?P<slug>[-\w]+)/', core_view.post_edit, name='edit_post'),
   url(r'(?P<slug>[-\w]+)/delete/',core_view.delete_post,name='delete_post'),
   url(r'result/', core_view.search, name="search"),
   url(r'category/(?P<slug>[-\w]+)/', core_view.category_detail, name='category_detail'),
   url(r'(?P<slug>[-\w]+)/comment/', core_view.add_comment_to_post, name='add_comment'),
  # url(r'comment/(?P<slug>\d+)/delete/', core_view.DelComment.as_view(), name='delete_coment'),
   #url(r'(?P<slug>\d+)/comment/delete/', core_view.delete_comment, name='delete_comment'),
   url(r'profile/(?P<username>[-\w]+)/', core_view.get_user_profile, name='uPage'),
   url(r'follow/(?P<username>[-\w]+)/', core_view.FollowToggle.as_view(), name="follow-toggle"),
   url(r'delete/(?P<username>[-\w]+)/',core_view.delete_user,name='delete_user'),
]

websiteForDVVS/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^home/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^sign-up/', include('account.urls')),
    url(r'^login/$', auth_views.login_required,name='login'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    #url('', RedirectView.as_view(url='home/', permanent=True)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/add_comment_to_post.html
{% extends 'base.html' %}
{% block body %}
<div class="container" >
<form method="post" >
<div class="row" id="reg" style="">
         <label style="font-size: 20px; color: black;margin-left: 1%;%">Написати коментар</label>{% csrf_token %}
          {% for foo in form %}
            {{ foo }}
          {% endfor %}
    <button id="send_bttn" type="submit" style="margin-top: 0px;" >Надіслати</button>
</div>
</form>
</div>
{% endblock %}

templates/pages/categories.html
<form method="GET" action="{% url 'blog:category_list' %}">
    {% for obj in objects_list %}
        <a href="#" class="list-group-item list-group-item-action">{{ obj.title }}</a>
    {% endfor %}
</form>

templates/pages/category_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}<title>{{ category.seo_title }}</title>{% endblock %}
{% block body %}

      <div  class="container"  style="background-color:rgb(0, 0, 0, 0.6);">
      <h1>{{ category.title }}</h1>
          	<br>
             {% for obj in items %}

                 {% if obj.status == 'Published' %}
            <div class="list-group">
			<a href="{% url 'blog:blog_detail' obj.slug %}" class="list-group-item list-group-item-action">
				<div class="row">
					<div class="col-2" id = "postPicDiv"><img id="postImage" src="{{ obj.image.url }}" class="img-fluid" defult="../blog/media/post_photos/colorful-octopus.jpg"></div>
					<div class="col-10">
						<h4>{{ obj.title }}</h4>
						<p id="article">{{ obj.body }}</p>
						<div class="row">
							<div class="col-4" id="heart"><img src="{% static 'image/heart2.png' %}" id="heartimg"><label id="likesamount"> {{ obj.likes.count }}</label></div>
							<div class="col-4" id="heart"><img src="{% static 'image/Comment.png' %}" id="heartimg"><label id="likesamount"> {{ obj.comments.count }}</label></div>
							<div class="col-4"><p id="date">{{ obj.created }}</p></div>
						</div>
					</div>
				</div>
			</a>

		</div>

{% endif %}
             {% endfor %}
      <br>
      </div>
{% endblock %}

templates/pages/pagination.html
{% if items.has_other_pages %}
    <div class="col-6 offset-3 text-center pagination-set">
        <nav aria-label="">
            <ul class="pagination">
                {% if items.has_previous %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ items.previous_page_number }}{% if query %}&q={{ query }}{% endif %}">&laquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link"><span>&laquo;</span></a></li>
                {% endif %}
                {% for i in page_range %}
                    {% if items.number == i %}
                        <li class="page-item active"><a class="page-link" href="#">{{ i }} <span
                                class="sr-only">(current)</span></a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}{% if query %}&q={{ query }}{% endif %}</a></li>
                    {% endif %}
                {% endfor %}
                {% if items.has_next %}
                    <li class="page-item"><a class="page-link" aria-label="Next"
                                             href="?page={{ items.next_page_number }}{% if query %}&q={{ query }}{% endif %}">&raquo;</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link"><span>&raquo;</span></a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endif %}

templates/pages/post_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}<title>{{ post.title }}</title>{% endblock %}
{% block body %}


<div class="container" style="background-color:rgb(0, 0, 0, 0.6);  padding-bottom: 20px;">
		<div class="row">
			<div class="col-11"><h2 style="color:white;">{{ post.title }}</h2></div>
        </div>
		<div class="row">
			<div class="col-7" id="userName"><h6 style="color:#d5d9e0;"><a href="{% url 'blog:uPage' post.author.username %}" style="color:#d5d9e0;">{{ post.author }}</a></h6></div>
            {% if post.author == request.user or request.user.is_staff  %}
             <div class="col-1" style="height: 25px;"><a  href="{% url 'blog:edit_post' slug=post.slug %}"><img src="{% static 'image/Editing-edit-icon.png' %}" style= "width: auto;height: 100%;opacity: 0.7;"></a></div>
			 <div class="col-1" style="height: 40px; float:right"><a href="{% url 'blog:delete_post' post.slug %}"><img src="{% static 'image/del.png' %}" style="width: auto;height: 100%;opacity: 0.8;"></a></div>
            {% endif %}
            <br>
            <div class="col-1"><label style="font-size: 13px; color:#e87153;">{{ post.status }}</label></div>
            <div class="col-2" style="font-size:12px;text-align: right; color:white;">published at: <label style="font-style:italic; color:red;">{{ post.created }}</label></div>
		</div>

		<div class="row">
			<div class="col-12" style="background-color:white; padding: 20px 20px 20px 20px;">
				<p>{{ post.body|linebreaks }} </p>
			</div>
		</div>

    <div class="row" style="background-color:white; padding-bottom: 15px;"><div class="col-12" id="heart"><a href = "{{ post.get_like_url }}"><button id="heart" ><img src="{% static 'image/heart2.png' %}" id="heartimg"></button></a><label style="font-weight:bold;">{{ post.likes.count }}</label></div></div>

    <br><br>
<div class="container">
      <div class="form-group">

            <a href = '{% url 'blog:add_comment' post.slug %}'><button id="send_bttn" type="submit" >Коментар</button></a>
          <br>
      </div>
    </div>
    <div class="row" style="background-color:white; padding-left: 30px; padding-right:30px; padding-bottom:10px;">

    <br><br>
         {% for comment in post.comments.all %}
			<div class="col-8">

				<a href="{% url 'blog:uPage' comment.author %}" style="color: #b2425c; font-weight:bold;">{{ comment.author }}</a>
			</div>
										      <!--   <div class="col-1"><a href="#"><button style="color:red; font-size:13px; font-weight:bold;margin-right: 0px;">delete</button></a></div>-->
			<div class="col-3" style="font-size:12px;text-align: right;">published at: <label style="font-style:italic; color:red;">{{ comment.created_date }}</label></div>
			<div class="col-12" style="background-color:#f4e8eb;">
				<p>{{ comment.text|linebreaks }} 	</p>
				          
			</div>
                    {% empty %}
    <p>No comments here yet </p>
                {% endfor %}
		</div>

	</div>
{% endblock %}

templates/pages/post_edit.html
{% extends 'base.html' %}
{% block title %}<title>New Post</title>{% endblock %}
{% block body %}
     <div id= "reg" class="container">
        <h1>New post</h1>
    <form method="POST" class="post-form" autocomplete="off" enctype="multipart/form-data">{% csrf_token %}
        {% for field in form %}
        <h5>{{ field.label_tag }}</h5>
          {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% endfor %}
        <button id="buttonS" type="submit" class="save btn btn-default" style = "margin-top: 2%; margin-bottom: 5%;">Save</button>

    </form>
     </div>
{% endblock %}

templates/pages/post_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
      <div  class="container"  style="background-color:rgb(0, 0, 0, 0.6);">
          	<br>
          {% for obj in items %}
                 {% if obj.status == 'Published' %}

		<div class="list-group">
			<a href="{% url 'blog:blog_detail' obj.slug %}" class="list-group-item list-group-item-action">
				<div class="row">
					<div class="col-2" id = "postPicDiv"><img id="postImage" src="{{ obj.image.url }}" class="img-fluid" defult="../blog/media/post_photos/colorful-octopus.jpg"></div>
					<div class="col-10">
						<h4>{{ obj.title }}</h4>
						<p id="article">{{ obj.body }}</p>
						<div class="row">
							<div class="col-4" id="heart"><img src="{% static 'image/heart2.png' %}" id="heartimg"><label id="likesamount"> {{ obj.likes.count }}</label></div>
							<div class="col-4" id="heart"><img src="{% static 'image/Comment.png' %}" id="heartimg"><label id="likesamount"> {{ obj.comments.count }}</label></div>
							<div class="col-4"><p id="date">{{ obj.created }}</p></div>
						</div>
					</div>
				</div>
			</a>

		</div>

{% endif %}
 {% endfor %}
      <br>
      </div>
     <div class="col-6 offset-3 text-center" style="margin-top: 1.5rem;">
    {% include 'pages/pagination.html' %}
     </div>
{% endblock %}

templates/pages/user_page.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}<title>{{ user.username }}</title>{% endblock %}

{% block body %}

		<div class="container"  style="background-color:rgb(0, 0, 0, 0.6);">

		<br><br>
        <div class="row">
			<div class="col-3">
			    <div id="userLabel"><h3> {{user.username}} </h3></div>
				<img id="profileImage" src="{{ profile.avatar.url }}" class="img-thumbnail">
				<input id="imageUpload" type="file"
                name="profile_photo" placeholder="Photo" required="" capture>
            {% if user == request.user %}
				<div class="row-3 bg-success"><button id="bttn" type="button" id="suka" class="btn btn-primary btn-block" value="Upload" onclick="return Upload()">Змінити фото</button></div>
                <div class="row-3"><a href="{% url 'blog:delete_user' user.username%}"><button id="settings" type="button" class="btn  btn-block" value="Upload" style="background-color:red; color:white;"onclick="DeleteFun()">Видалити сторінку</button></a></div>
			{% else %}
                <div class="row-3"><a href="{% url 'blog:follow-toggle' user.username %}"><button id="settings" type="button" class="btn  btn-block"  style="background-color:red; color:white;">Стежити</button></a></div>
            {% endif %}
                <div id="info"><label>Кількість підписників: </label><label id="subscribersAmount"> {{ profile.followers.count }}</label></div>
				<div id="info"><label>Кількість статей: </label><label id="articlesAmount">{{articles.count }}</label></div>
				<br>
				<div class="container" id="subscribers">
				<h5 id="subscribersHeader" style="color:white;">Підписники</h5>
					<div class="col" id="subscribersCol">

                        {% for foo in profile.followers.all %}
                        <div class="row" id="subscriberRow"><a href="{% url 'blog:uPage' foo.username %}" class="list-group-item-action"><label id="subscriberName">{{ foo.username }}</label></a></div>

                        {% endfor %}

						</div>
				</div>
			</div>
			<div class="col-8" id="divWithArticles">
            <div class="dropdown">     <!--ОТУТ ВОНО ПОЧИНАЄТЬСЯ-->
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
          style="width:100%;">
          Подробиці
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="width: 100%;">
            <div  style="width: 100%; padding-left:2%; padding-rihgt:2%;"><h5>Ім'я:</h5><p>{{ user.first_name }}  {{ user.last_name }}</p></div>
            <div style="width: 100%; padding-left:2%; padding-right:2%;"><h5>Дата народження:</h5><p>{{ profile.birth_date }}</p></div>
            <div  style="width: 100%; padding-left:2%; padding-right:2%;">
              <h5>Біо:</h5><p>{{ profile.bio }}</p>
            </div>
          </div>
        </div>
				<div class="col-12" id="headerDiv" style="text-align: center;"><h3 id="header">Мої статті</h3></div><br>

                <div class="list-group" id="articles">
                    {% for obj in articles %}
					<a href="{% url 'blog:blog_detail' obj.slug %}" class="list-group-item list-group-item-action">{{ obj.title }} <br>
						<div class="row">
							<div class="col-5" ><img id="heart" src={% static 'image/heart2.png'%} id="heartimg><label id="likesamount">{{ obj.likes.count }}</label></div>
							<div class="col-7"><p id="date">{{ obj.created }}</p></div>
						</div>
					</a>
                    {% endfor %}
				</div><br>

			</div>
        </div>
	</div>

<script type="text/javascript">
	function DeleteFun(){alert("Сторвнку видалено!");}
$("#bttn").click(function(e) {
    $("#imageUpload").click();
});

function fasterPreview( uploader ) {
    if ( uploader.files && uploader.files[0] ){
          $('#profileImage').attr('src',
             window.URL.createObjectURL(uploader.files[0]) );

    }
}

$("#imageUpload").change(function(){
    fasterPreview( this );
});
</script>
{% endblock %}