account/urls.py
from django.conf.urls import url
from . import views as core_views

app_name = 'account'

urlpatterns = [
    url(r'^$',core_views.signup,name='signup'),


]

blog/urls.py
from django.conf.urls import url
from . import views as core_view
app_name = 'blog'

urlpatterns = [
   url(r'^$', core_view.post_list,  name="blog_list_view"),
   url(r'post/(?P<slug>[-\w]+)/', core_view.post_detail, name="blog_detail"),
   url(r'(?P<slug>[-\w]+)/like/', core_view.PostLikeToggle.as_view(), name="like-toggle"),
   url(r'new-post/', core_view.post_new, name="new_post"),
   url(r'edit/(?P<slug>[-\w]+)/', core_view.post_edit, name='edit_post'),
   url(r'(?P<slug>[-\w]+)/delete/',core_view.delete_post,name='delete_post'),
   url(r'result/', core_view.search, name="search"),
   url(r'category/(?P<slug>[-\w]+)/', core_view.category_detail, name='category_detail'),
   url(r'(?P<slug>[-\w]+)/comment/', core_view.add_comment_to_post, name='add_comment'),
  # url(r'comment/(?P<slug>\d+)/delete/', core_view.DelComment.as_view(), name='delete_coment'),
   #url(r'(?P<slug>\d+)/comment/delete/', core_view.delete_comment, name='delete_comment'),
   url(r'profile/(?P<username>[-\w]+)/', core_view.get_user_profile, name='uPage'),
   url(r'follow/(?P<username>[-\w]+)/', core_view.FollowToggle.as_view(), name="follow-toggle"),
   url(r'delete/(?P<username>[-\w]+)/',core_view.delete_user,name='delete_user'),
]

websiteForDVVS/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^home/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^sign-up/', include('account.urls')),
    url(r'^login/$', auth_views.login_required,name='login'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    #url('', RedirectView.as_view(url='home/', permanent=True)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>

{% load staticfiles %}
<html>
<head>
    <link rel="icon" href="{% static 'image/icon.png' %}">

	<link rel="stylesheet" href={% static 'stylesheet/base.css' %}>
    <link rel="stylesheet" href={% static 'stylesheet/user-page.css' %}>
    <link rel="stylesheet" href ={% static 'stylesheet/lents.css'%}>
    <link rel="stylesheet" href ={% static 'stylesheet/new-post.css'%}>
    <link rel="stylesheet" href={% static 'stylesheet/post_det.css' %}>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% block title %}<title>LitLib</title>{% endblock %}
</head>
<body background={% static 'image/background.png'%} onload="values()">

	<nav class="navbar navbar-expand-sm bg-dark navbar-dark ">
       <a href={% url 'blog:blog_list_view' %}><button id="main" class="navbar-brand" ><img id="ico" src="{% static 'image/icon.png' %}"  style="background-color:white; height: 50px;"></button></a>     <!--golovna storinka-->
     <div>
  	   <ul class="navbar-nav mr-auto">
         <li class="nav-item active">

            {% if user.is_authenticated %}
                {% if request.user.is_staff %}
                    <li><a href ={% url 'admin:index' %}><button id="listButton" class="btn btn-success ml-auto">Панель Адміна</button></a></li>
                {% endif %}
                <li><a href ={% url 'blog:new_post' %}><button id="listButton" class="btn btn-success ml-auto">Нова стаття</button></a></li>
                <li><a href ={% url 'blog:uPage' request.user.username %}><button id="listButton" class="btn btn-success ml-auto"> {{request.user.username}}</button></a></li>
                <li><a href="{% url 'logout' %}?next=/home"><button id="listButton" class="btn btn-success ml-auto">Вихід</button></a></li>
            {% else %}
                <li> <a href="{% url 'login' %}"> <button type="submit"  id="listButton"class="btn btn-success ml-auto"> Увійти</button></a></li>
                <li><a href={% url 'account:signup' %}  ><button  id="listButton" class="btn btn-success ml-auto"  >Реєстрація</button></a></li>
            {% endif %}

        </ul>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>

        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
           <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                    <form  id="formForSearch" method="GET" action="{% url 'blog:search' %}">
                        <button id="findButton"  style="border-radius: 10px 10px 10px 10px;padding: 5px" class="btn-success" >Знайти</button>
                        <input  id ="inputFind"  style="border-radius: 10px 10px 10px 10px;padding: 3px"name="q" value="{{ request.GET.q }}"  type="text" placeholder="Пошук">
                    </form>
                </li>

        </ul>
    </div>
</nav>
<!-- Висувна менюшка -->

<div class="row" style="padding-right: 1%; padding-left:1%;">

	<div class="list-group" id="icoDiv" style="width:5%;">
		<button id="dropbtn"  value="Click" onclick="fun()" style=""><img src="{% static 'image/krug2.png' %}" id="ico" style="height: 50px;"></button>
    <!----> {% for obj in category %}
        <a href="{% url 'blog:category_detail' obj.slug %}" class="list-group-item list-group-item-action" style="visibility:hidden;">{{ obj.title }}</a>
    {% endfor %}
        <!-- тут має виводити категорії-->
  }

	</div>

    {% block body %}

    <!--Руками не рухати-->

    {% endblock %}
</div>
<!----------------------------------------------------------------------------------------------------------------->




</body>
<footer>
    <script type="text/javascript" language="javascript">
		$(document).ready(function() {
			var div1 = document.getElementById("icoDiv");
			var parentID = document.getElementById('icoDiv');
			var subs = parentID.getElementsByClassName('list-group-item list-group-item-action');
			for(var i = 0; i < subs.length; i++){
					var a = subs[i];
					a.style.visibility = 'hidden';
				}

		});
        function fun() {
            var div1 = document.getElementById("icoDiv");
			var parentID = document.getElementById('icoDiv');
			var subs = parentID.getElementsByClassName('list-group-item list-group-item-action');

			if (div1.style.width == "5%")
			{
				w = div1.style.width;
				div1.style.width = "15%";
				for(var i = 0; i < subs.length; i++){
					var a = subs[i];
					a.style.visibility = '';
				}

			}
			else
			{
				div1.style.width = w;
				for(var i = 0; i < subs.length; i++){
					var a = subs[i];
					a.style.visibility = 'hidden';
				}

			}
			return false;
        }


    </script>
</footer>
</html>